<a href="https://colab.research.google.com/github/HeYLoW111/Intro-collab/blob/main/Zadania.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import numpy as np
a = np.array([1,2,3])
b = np.zeros([3,3])
print(b)
c = np.ones([2,2])
print(c)
d = np.full([4,4], 8)
d
e = np.arange(0, 10, 2) #to samo jest domyślnie jako range()
e
f = np.linspace(0, 10, 20)
f
g = np.array([[1, 2, 3, 4], [2, 3, 4, 5], [3, 4, 5, 6], [4, 5, 6, 7]])
g[:3,1:3]

s = np.sum(d)
s
m = np.mean(g)
m


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]


4.0

In [9]:
import numpy as np
a = np.arange( start = 5, stop = 1000, step = 17 )
print(a)

np.linspace(1,20,50)


A = np.array([1, 4, 5, 2])
B = np.array([-2, 5, 6, 5])
print(A + B) # domyślnie jest element by element



[  5  22  39  56  73  90 107 124 141 158 175 192 209 226 243 260 277 294
 311 328 345 362 379 396 413 430 447 464 481 498 515 532 549 566 583 600
 617 634 651 668 685 702 719 736 753 770 787 804 821 838 855 872 889 906
 923 940 957 974 991]
[-1  9 11  7]


TypeError: Field elements must be 2- or 3-tuples, got '4'

In [14]:
C = np.array([[2, 5],[4, 6]])
D = np.array([[2, 9],[1, 6]])
np.dot(C, D) #mnożenie macierzy algebraiczne
print(C.dot(D))     #to jest to samo
print(D.dot(C))
print( C @ D)  #i to też

[[ 9 48]
 [14 72]]
[[40 64]
 [26 41]]
[[ 9 48]
 [14 72]]


In [29]:
np.random.seed(0)
np.random.randn()
np.random.randn(10)
A = np.random.randn(10,4)
np.random.rand() # to rozklad jednostajny
np.random.randint(10) # zwraca int 0-10
np.random.randint(low = 10, high = 20, size = 10)

np.random.choice([4, 2, 1, 3, 5])
np.random.choice(["a", "V", "F"])

np.random.shuffle(A)
A

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ]])

In [51]:
np.exp(4)
np.all([2, 3, 1])
np.any([0, 0, 0])

A = [4, 2, 1]
A[np.argmax(A)]
np.argmin([4, 2, 1]) #zwracają indeksy

np.argsort(A)  #podaje posortowane indeksy


T = np.arange(20).reshape(4, 5)
#for row in T:
 #   print(row[2])

#for item in T.flat:
#    print(item)

T.ravel()

T.T


T[T > 9]

np.bitwise_and(T > 5, T < 10)
np.bitwise_or(T < 5, T > 10)


array([[ True,  True,  True,  True,  True],
       [False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])